### PR TITLE
Homepage design

### LINKED ISSUE #140: Home page design
After our discussion, I do agree that a slightly different home page landing experience could be better and that pulling out the featured lessons to be separate from the lesson gallery makes sense. It seems like there are potentially four things to include at the top of the home page.

- Brief words about what the site/channel is.
    - Possibility: "3blue1brown videos aim to illustrate the sense of creativity and discovery in math, presented with a highly visual style."
- Latest video
- Featured content
    - Maybe as a shelf beneath the top spotlight?
- Lesson gallery

The big benefit of the current single-video-in-the-spotlight vibe is its minimalism. This is potentially a nice way to set the tone of the minimalism of the content itself, which often aims to just display what is needed and nothing more. Even if we want to include all four things above, it would be best to do so in a way that still sets this tone.

@kurtbruns, if you have a chance, would you like to quickly throw together a wireframe or two to work from? I think the answer could be pretty simple, maybe just the words and latest video presented side-by-side up top, with a shelf of ~4 featured lessons below, followed by the lesson gallery. But sometimes the devil's in the details.

### PR DESCRIPTION
**Pull request by PullJosh**
Website change review checklist:
- [x] I have requested a review from the appropriate persons
- [x] I have checked that my changes work in the preview
- [x] I have checked that the rest of the site is still functioning in the preview
- [x] I have checked that my content/code is consistent with existing content/code
- [x] I have used components in the places and ways they are intended (see the readme)
- [x] I have formatted all of my code with Prettier

This pull request:
- Adds a new homepage design with a rotating carousel of featured lessons
- Changes the way that interactives are sized on the page. Interactive authors can now write their code as if the interactives are a fixed size (such as, for example, 880x500 pixels), and then the `<Interactive>` component will automatically scale the contents similarly to how images and videos are scaled to fit within the page. (This was necessary to make the neural network interactive work both in the article and on the homepage.)
- Closes #140

### CODE REVIEW

**Comment by 3b1b** [comment]
I know this is only partially finished, so perhaps too early for feedback, but here are some nates as I look at it:
- Looking at it now, I might abbreviate the text simply to "Lessons about creativity and discovery in math."
- I'd have not autoscrolling on the featured carrosel.
- For cases where the featured item does not match the 16x9 aspect ratio, such as the neural nets one, I'd match the height instead of the width.
- Rather than cycling around, I'd say don't display the left arrow for the first item in the list and don't display the right arrow for the last item in the list.

**Comment by PullJosh** [comment]
Now's a perfect time for feedback. And I think every point you made is smart. I will implement it tomorrow.

**Comment by PullJosh** [comment]
@3b1b Okay, I've implemented your suggestions: https://deploy-preview-145--3blue1brown.netlify.app/

Thoughts now?

**Comment by 3b1b** [comment]
Looks great, thanks!  Only two notes things before merging.

- Instead of darkening the left arrow when it's inactive, I'd remove it entirely.
- For some reason, the animations don't play on mobile for me, on Chrome/Safari/Brave. I imagine this could be solved just by making them gifs, but gifs tend to be some combination of lower quality and more data.

**Comment by PullJosh** [comment]
> Instead of darkening the left arrow when it's inactive, I'd remove it entirely.

I actually like the symmetry of having both arrows present. It helps indicate that scrolling is an option, you've just reached the end of the slides.

> For some reason, the animations don't play on mobile for me, on Chrome/Safari/Brave. I imagine this could be solved just by making them gifs, but gifs tend to be some combination of lower quality and more data.

Oh, weird. Me too. I'll try to figure it out.

**Comment by 3b1b** [comment]
> I actually like the symmetry of having both arrows present...

Works for me, it's a very soft opinion.

**Comment by PullJosh** [comment]
I'm pretty sure the video issues are fixed on mobile. It works on my phone now (and it didn't before).

**Comment by 3b1b** [comment]
> I'm pretty sure the video issues are fixed on mobile. It works on my phone now (and it didn't before).

Yup, works on mine too. I'm happy with merging that if you are.

**Pull request merged**
