### PR TITLE
Blog and podcast

### LINKED ISSUE #171: Create pages `/blog` and `/podcast`
The extras page currently links to these, but they don't exist.

### PR DESCRIPTION
**Pull request by PullJosh**
Website change review checklist:
- [ ] I have requested a review from the appropriate persons
- [ ] I have checked that my changes work in the preview
- [ ] I have checked that the rest of the site is still functioning in the preview
- [x] I have checked that my content/code is consistent with existing content/code
- [x] I have used components in the places and ways they are intended (see the readme)
- [x] I have formatted all of my code with Prettier

This pull request:
- [x] Creates `/blog`
- [x] Transfers a bunch of pages from the old site over in blog post form
- [x] Creates `/podcast`
- Closes #171

### CODE REVIEW

**Comment by PullJosh** [comment]
@3b1b This PR has reached a stage were some feedback would be helpful. (In particular, I wasn't really sure what to do for the blog home page, so it's still quite rough.)

**Comment by 3b1b** [comment]
Thanks!  Here are some notes:

- Rather than the full "Listen on ____" buttons...

    Screen Shot 2021-07-23 at 11 19 40 AM

    I would just have the podcast app logos, with tooltips giving their names.

    image

- You know, I think instead of having them at the top of the extras page, both should exist in links at the header, and we should remove the "subscribe" button from the header to help make room. That is, the header should read:
    - Lessons
    - Podcast
    - Blog
    - Extras
    - Contact
    - About
    - Store
    - Support

- [Here's a vector version of the logo](https://www.dropbox.com/s/1vc8p2z78vm0fqw/VectorLogo.svg?dl=0).
- For the blog, I'd put the dates on the left. 
 
    image

    Then also probably align the titles by the left.
    
- On the blog page itself, I would remove the "<- blog" link so that the date can be centered, and place it instead in the upper left corner of the screen. If the blog is actually in the header, that might even be redundant.

**Comment by PullJosh** [comment]
Any preference on the tooltip text for the "Blog" and "Podcast" links in the header?

**Comment by 3b1b** [comment]
Looks good to me. I'll probably do a sweep through to think about the wording on various places of the site later, so if I have any other thoughts on the tooltips I'll handle it then.

Merge away, if you'd like.

**Pull request merged**
