### PR TITLE
Add free response component

### LINKED ISSUE #159: Free response component
Have a way to ask questions which invites users to type their own answer. It would probably be something super simple, maybe like [this](https://itempool.com/3b1b/c/yfTpkVn5WpN)?

Upon clicking "check", the user would see an example answer, perhaps labeled as "Possible answer"

It may be worth having a tiny explanation of the widget somewhere, say a small question mark in the corner of the component with a tooltip, where we say explicitly that this is not a checked or saved answer, it's just a prompt for readers to write down and clarify their own thinking.

### PR DESCRIPTION
**Pull request by PullJosh**
Website change review checklist:
- [x] I have requested a review from the appropriate persons
- [ ] I have checked that my changes work in the preview
- [x] I have checked that the rest of the site is still functioning in the preview
- [x] I have checked that my content/code is consistent with existing content/code
- [x] I have used components in the places and ways they are intended (see the readme)
- [x] I have formatted all of my code with Prettier

This pull request:
- Adds a free response component
- Includes a free response question in the testbed
- Closes #159

### CODE REVIEW

**Comment by 3b1b** [comment]
This looks nice, and I love the tooltip text. Just two quick notes:

- I'd make the submit button smaller, and place it outside the textbox. I think hanging off the lower right might be fitting.
- Similarly, I'd put the question mark outside the box, say above the box aligned to the right.

The choice to lock the text upon submitting was an interesting one. My initial reaction was that it felt unnecessary, but looking at it more it seems to give a kind of significance to the submit button which would otherwise not really be there as much.

**Comment by PullJosh** [comment]
Okay, I've changed the styles based on your recommendations. I wasn't confident that it would look good, but now that I see it this way I really like it. 🤩

> The choice to lock the text upon submitting was an interesting one. [...]

That's interesting! I didn't even give that feature a second thought. It just seemed necessary.

(I think the lesson here is that having more than one set of eyeballs on something really helps.)

**Comment by PullJosh** [comment]
I just realized you can't see the testbed on the preview. So here's a screenshot for anyone who is too lazy to check out the branch:

image

**Comment by 3b1b** [comment]
Looks good to me, merge away.

**Pull request merged**
